title: StackDB
description: StackDB documentation and examples

collections:
  - examples

# Don't process the cardb React app, it's in the ../cardb repo.
exclude:
  - CNAME

plugins:
  - jekyll-redirect-from
